# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
modelSelection_trans_mat <- function(mat_pred, obj_pred, Rt, seqLen, K, obj_Kmodel, gamma, v_muLBI, clamp) {
    .Call('_modelselect_modelSelection_trans_mat', PACKAGE = 'modelselect', mat_pred, obj_pred, Rt, seqLen, K, obj_Kmodel, gamma, v_muLBI, clamp)
}

#' @export
computeR <- function(E_obs, Rt, muLBI, clamp) {
    invisible(.Call('_modelselect_computeR', PACKAGE = 'modelselect', E_obs, Rt, muLBI, clamp))
}

